name = "sgaesthetix"
main = ".open-next/worker.js"
compatibility_date = "2026-06-05"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[services]]
binding = "WORKER_SELF_REFERENCE"
service = "sgaesthetix"   # must match name above

[images]
binding = "IMAGES"

[vars]
NEXT_PUBLIC_SUPABASE_URL = "https://bnqflkoqeaowwcguakxs.supabase.co"
NEXT_PUBLIC_SUPABASE_ANON_KEY = "sb_publishable_f4wVAMOajjuxln9cQtsI-w_vlaKiS52"
NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME = "dp1vgjhsq"
NEXT_PUBLIC_CLOUDINARY_UPLOAD_PRESET = "sg_aesthetix"
NEXT_PUBLIC_WA_NUMBER = "+51902734463"
NEXT_PUBLIC_GOOGLE_CLIENT_ID = "867235107831-g119662qpnot86bkje0c0t5cu32ceip6.apps.googleusercontent.com"